### ISSUE TITLE
some ideas about playlist editor

### ISSUE THREAD

**Issue by zzz6839** [ComputerElite/BM#6]
The playlist editor is very helpful to manage the BMBF,  I hope we could have more functions

1. I read the wiki page and post my questions on discord but I wasn't able to find the "delete songs" button rather remove songs.
2.  Can we use drag and drop to add more songs to the playlist? that's more efficient.
3. Add maximize button to enlarge the window could help when reading the information about the songs  
4. Add a tick box in front of the songs' name for the multi-select function
5. function keys support on keyboard such as click "delete" to uninstall the songs.

I really appreciate BM Manager, it's a time saver! Cheers for the cool tool! 🍺

**Comment by ComputerElite** [comment]
1. I renamed it. forgot to update the wiki
2. not entirely sure how I'd do it but I'll look into it
3. not really possible with the current way the ui is set up.
4. you can use ctrl click instead of a tick box. but I think I didn't implement that yet. Will add it
5. with that I'd still let a pop up pop up so you don't do anything on accident. tho I'd change that if you want

Tell me your thought

**Comment by ComputerElite** [comment]
currently on point 5 (doing stuff via key presses). What do you (or anyone) want to be doable? Currently I got add song to playlists and remove song from playlist (via left and right arrow key).

**Comment by zzz6839** [comment]
thanks for the fast reply, here is my thought.

1. "Remove song" is kinda confusing, "remove song from the playlist" is better, could add a "delete song from the device" button(please refer to the conceptual image)  
2. drag and drop function would be like that(don't need to be the same):
![C2apture](https://user-images.githubusercontent.com/57741549/131229848-81a1821f-c92a-4b92-af2f-212cd6010cbd.jpg)



3. it's ok, not a big deal
4. also ok, need to add instruction (refer to the image)
5. can add a "undo delete" button on top of the "delete song from the device" to prevent any accident, pop up wont be necessary(you still need to sync it with the device after all).

**Comment by ComputerElite** [comment]
1. fun fact. that confused me as well rn lmao. I may do a slightly changed layout and will add a delete song button (forgot it after reworking the ui)
2. It's not a main focus as you can now use arrow keys and do multi select which will speeds things up. It may be added in a future version of BMBF Manager
4. yeah that'll be added to the wiki
5. for deleting songs I will need to do some testing to see if I can do that via the BMBF config bc of the runtime song loader changes. otherwise it'll be done via adb and not saved when you save but right away which won't be undoable

**Comment by ComputerElite** [comment]
yeah looks like songs have to be deleted via adb

**Comment by ComputerElite** [comment]
![image](https://user-images.githubusercontent.com/71177995/131230698-8c0de3fa-6039-4cbb-b936-3a0e86b2d912.png)
alright that should be mostly how you wanted it. Still have to polish up some little things

**Comment by ComputerElite** [comment]
alright it's now released. If you got any more issues feel free to open this issue again https://github.com/ComputerElite/BM/releases/tag/1.16.6
